workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'develop'
    

stages:
  - frontend
  - backend

frontend:
  stage: frontend
  only:
    - develop
    - main
  trigger:
    include: front-end/.gitlab-ci.yml


backend:
  stage: backend
  only:
    - develop
    - main
  trigger:
    include: backend-base-de-datos/.gitlab-ci.yml
